ATTENTION:
  LINEAR_EMB: 512
DGCNN:
  DROPOUT: 0.5
  EMB_DIM: 1024
  K: 20
EXP:
  DATASET: modelnet40
  NAME: exp1
  NUMPY_RANDOM_SEED: 7
  NUM_POINTS: 1024
  TORCH_RANDOM_SEED: 1
  WORKING_DIR: working_dir
TEST:
  BATCH_SIZE: 16
TRAIN:
  BATCH_SIZE: 64
  LR: 0.01
  MIXUP_LEVEL: feature
  N_DIV: 3
  N_EPOCHS: 500
  OPT: sgd